server:
  readTimeout: 10
  writeTimeout: 10
  port: ":8080"
  maxHeaderBytes: 1048576 # 1MB大小的头文件
mysql:
  host: "47.93.83.136"
  port: 3306
  user: "root"
  password: "123456"
  database: "gorm"
redis:
  addr: "47.93.83.136"
  port: 6379
  password: "123456"
  db: 0
  protocol: 3
jwt:
  signing-key: "Wwhds_one"
  expires-time: "1h"
  buffer-time: "10m"
  issuer: "Wwhds"


